server:
  port: 9099
spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
      config:
          file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心的路由功能
      routes:
        - id : consumer
          uri: lb://consumer-demo
          predicates:
            - Path=/consumer-demo/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
        - id: sentinel
          uri: lb://sentinel-demo
          predicates:
            - Path=/sentinel-demo/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
        - id: activity
          uri: lb://activity-consumer-demo
          predicates:
            - Path=/activity-consumer-demo/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
        - id: test-paper
          uri: lb://test-paper-consumer-demo
          predicates:
            - Path=/test-paper-consumer-demo/**
            - Method=GET,POST
          filters:
            - StripPrefix=1

#  main:
#    allow-bean-definition-overriding: true

#  config:
#    import: nacos:gateway_nacos_config.yml
#    gateway_nacos_config.${spring.cloud.nacos.config.file-extension}
