server:
  port: 9094
spring:
  application:
    name: test-paper-consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
management:
  endpoints:
    web:
      exposure:
        exclude: "*"