server:
  port: 9097
spring:
  application:
    name: consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
